// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaTM7ZwPr4qfJl7Pj7GZInOgLWEZUPq-s',
    appId: '1:962179181625:web:e49731a21f7c20ab6031e8',
    messagingSenderId: '962179181625',
    projectId: 'package-info-app',
    authDomain: 'package-info-app.firebaseapp.com',
    storageBucket: 'package-info-app.appspot.com',
    measurementId: 'G-WJ7G0E1T3D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeeXDeFJlDt4-uVXS61VyE54zkmoijWfo',
    appId: '1:962179181625:android:c152307aa73392a86031e8',
    messagingSenderId: '962179181625',
    projectId: 'package-info-app',
    storageBucket: 'package-info-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwreAikoMXGC0360WNgN-9y2wbKrll1ro',
    appId: '1:962179181625:ios:a8f1877e74a278266031e8',
    messagingSenderId: '962179181625',
    projectId: 'package-info-app',
    storageBucket: 'package-info-app.appspot.com',
    iosBundleId: 'com.example.allNetworkPackages',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwreAikoMXGC0360WNgN-9y2wbKrll1ro',
    appId: '1:962179181625:ios:a8f1877e74a278266031e8',
    messagingSenderId: '962179181625',
    projectId: 'package-info-app',
    storageBucket: 'package-info-app.appspot.com',
    iosBundleId: 'com.example.allNetworkPackages',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaTM7ZwPr4qfJl7Pj7GZInOgLWEZUPq-s',
    appId: '1:962179181625:web:5ae8d99ec2f56b2f6031e8',
    messagingSenderId: '962179181625',
    projectId: 'package-info-app',
    authDomain: 'package-info-app.firebaseapp.com',
    storageBucket: 'package-info-app.appspot.com',
    measurementId: 'G-GQ5MWWM4MH',
  );
}
